tenants:
  - name: lara-dev-minio-tenant
    namespace: lara-dev
    pools:
      - servers: 1
        volumesPerServer: 1
        size: 10Gi
        extraEnv:
          - name: MINIO_IDENTITY_OPENID_CONFIG_URL
            value: "https://keycloak.default.svc.cluster.local:8080/<realm-name>/.well-known/openid-configuration"
          - name: MINIO_IDENTITY_OPENID_CLIENT_ID
            value: "<TODO>"
          - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: oidc-secret
                key: client-secret
          - name: MINIO_IDENTITY_OPENID_SCOPES
            value: "openid,profile,email"
