apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admins-role
rules:
  - apiGroups: [""]
    resources: ["pods", "deployments", "services", "httproutes", "secrets", "persistentvolumeclaims", "gateways"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admins-binding
subjects:
  - kind: Group
    name: cluster-super-admin # keycloak user group name
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admins-role
  apiGroup: rbac.authorization.k8s.io