apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lara-development
  name: read-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lara-development
  name: write-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "persistentvolumeclaims",]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-role-bindind
  namespace: lara-development
subjects:
- kind: Group
  name: dev-lara-developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: write-role-bindind
  namespace: lara-development
subjects:
- kind: Group
  name: dev-lara-deployer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: write-role
  apiGroup: rbac.authorization.k8s.io
