apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cloud-routes
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "cloud.lara.test.local"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /pipelines
    backendRefs:
    - name: woodpecker
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /auth/
    backendRefs:
    - name: keycloak
      port: 80
