apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cloud-routes
  namespace: cloud
spec:
  parentRefs:
  - name: lara-gateway
  hostnames:
  - "auth.cloud.lara.local"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: keycloak
      port: 80


  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /pipelines
  #   backendRefs:
  #   - name: woodpecker
  #     port: 80