apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cloud-routes
  namespace: cloud
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/forwarded-headers: "true"
spec:
  parentRefs:
  - name: lara-gateway
    sectionName: https
  hostnames:
  - "auth.cloud.bonfimalan.com.br"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: keycloak
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cloud-http-redirect-route
  namespace: cloud
spec:
  parentRefs:
  - name: lara-gateway
    sectionName: http
  hostnames:
  - "auth.cloud.bonfimalan.com.br"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
