apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-httproute
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "www.example.com" # TODO add the host here using the cloudflare tunnel hostname and internal dns
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /pipelines
    backendRefs:
    - name: woodpecker
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /auth
    backendRefs:
    - name: keycloak
      port: 80
