apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lara-routes
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "dev.lara.test.local" # TODO add the host here using the cloudflare tunnel hostname and internal dns
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /minio
    backendRefs:
    - name: minio # TODO update this based in the name space
      port: 80
